(()=>{
'use strict';
const api=window.__FW_MULTI_WAVE,C=window.__FW_WAVE_CONFIG,G=window.__FW_WAVE_GEOMETRY,pipeline=window.__FW_RENDER_PIPELINE,canvas=document.getElementById('canvas');
if(!api||!C||!G||!pipeline||!canvas)return;
const ctx=canvas.getContext('2d'),U=window.__FW_UTILS||{},clamp=U.clamp||((v,a,b)=>Math.max(a,Math.min(b,v))),normalizeHex=U.normalizeHex||(v=>String(v||'').replace(/^#/,'').toUpperCase().replace(/[^0-9A-F]/g,'').slice(0,6)),toast=window.__FW_TOAST||(()=>{}),{DEFAULT_FILL,FILLABLE}=C,el=id=>document.getElementById(id);
const imageState=new Map();let ui=null,cropDrag=null,lastFrame={energy:{bass:0,mid:0,treble:0,beat:0,time:0}},lastLayerIds=[],lastActiveId=null;
function fillFromLayer(layer){const p=layer?.plate||{},color=p.tone==='light'?'#f2eee5':(/^#[0-9a-f]{6}$/i.test(String(p.color||''))?p.color:DEFAULT_FILL.color);return{enabled:!!p.enabled,color,opacity:clamp(Number.isFinite(+p.opacity)?+p.opacity:DEFAULT_FILL.opacity,20,100)}}
const defaultImageConfig=()=>({type:'color',imageX:50,imageY:50,imageZoom:100});
function layerImageConfig(layer){if(!layer)return defaultImageConfig();if(!imageState.has(layer.id))imageState.set(layer.id,{...defaultImageConfig(),resource:null});return imageState.get(layer.id)}
function activeInfo(){const layers=api.getLayers(),index=api.getActiveIndex(),layer=layers[index];return layer?{index,layer}:null}
const current=()=>fillFromLayer(activeInfo()?.layer);function currentImage(){const info=activeInfo();return info?layerImageConfig(info.layer):defaultImageConfig()}
function patch(value){const info=activeInfo();if(!info)return false;const next={...current(),...value};return api.updatePlate(info.index,{enabled:!!next.enabled,color:next.color,opacity:clamp(+next.opacity||DEFAULT_FILL.opacity,20,100),tone:'custom',shape:'follow',softness:0,shadow:0,size:100})}
function patchImage(value){const info=activeInfo();if(!info)return false;const cfg=layerImageConfig(info.layer);Object.assign(cfg,value||{});cfg.type=cfg.type==='image'?'image':'color';cfg.imageX=clamp(Number.isFinite(+cfg.imageX)?+cfg.imageX:50,0,100);cfg.imageY=clamp(Number.isFinite(+cfg.imageY)?+cfg.imageY:50,0,100);cfg.imageZoom=clamp(Number.isFinite(+cfg.imageZoom)?+cfg.imageZoom:100,100,300);document.dispatchEvent(new CustomEvent('fw:fill-image-change',{detail:{index:info.index}}));return true}
function syncHex(){if(ui)ui.hex.value=normalizeHex(ui.color.value)||'17191C'}
function syncAvailability(){if(!ui)return;const info=activeInfo(),ok=!!info&&FILLABLE.has(info.layer.style);[ui.enabled,ui.type,ui.color,ui.hex,ui.useWave,ui.opacity,ui.upload,ui.zoom,ui.resetCrop].forEach(x=>{if(x)x.disabled=!ok});ui.block.classList.toggle('disabled',!ok);if(!ok){ui.note.textContent='Fill is available for Brush Ring, Smooth Ring, Radial Bars and Orbit Dots.';return}const img=currentImage();ui.note.textContent=img.type==='image'?(img.resource?'Image and mask pulse together with the waveform. In Waveform mode, drag inside the image to choose the crop.':'Upload an image for this waveform. Until then, the color fill remains visible.'):'Color fill follows the same audio-reactive contour as the waveform.'}
function syncUI(){if(!ui)return;const c=current(),img=currentImage(),image=img.type==='image';ui.enabled.checked=c.enabled;ui.color.value=c.color;ui.opacity.value=c.opacity;ui.opacityValue.textContent=c.opacity+'%';ui.zoom.value=img.imageZoom;ui.zoomValue.textContent=img.imageZoom+'%';ui.imageName.textContent=img.resource?.name||'No image selected';ui.colorControls.hidden=image;ui.imageControls.hidden=!image;ui.type.value=image?'image':'color';syncHex();syncAvailability()}
function applyHex(){const clean=normalizeHex(ui.hex.value);if(!clean)return false;ui.hex.value=clean;ui.color.value='#'+clean;patch({color:'#'+clean});return true}
function mountStyles(){if(el('fw-wave-fill-style'))return;const s=document.createElement('style');s.id='fw-wave-fill-style';s.textContent=`.wave-fill-block{margin:10px 0;padding:10px;border:1px solid #2b3033;border-radius:10px;background:rgba(8,12,14,.58)}.wave-fill-title{margin:0 0 8px}.wave-fill-enable{display:flex!important;align-items:center;gap:7px;font-size:10px!important;font-weight:600;color:#ddd3c5!important;margin:0 0 9px!important}.wave-fill-type{display:block!important;margin:0 0 9px!important}.wave-fill-type select{margin-top:5px}.wave-fill-row{display:grid;grid-template-columns:46px minmax(72px,1fr) minmax(112px,auto);align-items:center;gap:6px}.wave-fill-row input[type=color]{width:46px;height:36px;border:1px solid #30363a;border-radius:8px;background:#0b0f11;padding:3px}.wave-fill-row input[type=text]{height:36px;margin:0!important;padding:0 9px!important;border:1px solid #30363a!important;border-radius:8px!important;background:#0b0f11!important;color:#eee6da!important;font:600 10px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace!important;letter-spacing:.06em;text-transform:uppercase}.wave-fill-row .button,.wave-fill-upload-row .button{height:36px;min-height:36px}.wave-fill-image{display:grid;gap:8px}.wave-fill-upload-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;align-items:center}.wave-fill-image-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:0 9px;height:36px;line-height:36px;border:1px solid #30363a;border-radius:8px;background:#090d0f;color:#a79f94;font-size:9px}.wave-fill-zoom{display:block!important;margin:0!important}.wave-fill-image-actions{display:flex;justify-content:flex-end}.wave-fill-opacity{display:block!important;margin:9px 0 0!important}.wave-fill-note{margin:6px 0 0!important}.wave-fill-block.disabled{opacity:.55}.wave-fill-block.disabled .wave-fill-title{color:#777}@media(max-width:820px){.wave-fill-row{grid-template-columns:46px 1fr}.wave-fill-row .button{grid-column:1/-1;width:100%}.wave-fill-upload-row{grid-template-columns:1fr}.wave-fill-upload-row .button{width:100%}}`;document.head.appendChild(s)}
function mount(){const card=el('waveStyle')?.closest('.card'),colorRow=card?.querySelector('.color-row');if(!card||!colorRow)return false;mountStyles();if(!el('waveFillEnabled')){const block=document.createElement('div');block.className='wave-fill-block';block.innerHTML=`<div class="section-label wave-fill-title">FILL</div><label class="wave-fill-enable"><input id="waveFillEnabled" type="checkbox" /> Fill inside waveform</label><label class="wave-fill-type">Type<select id="waveFillType"><option value="color">Color</option><option value="image">Image</option></select></label><div class="wave-fill-color-controls"><div class="wave-fill-row"><input id="waveFillColor" type="color" value="#17191c" aria-label="Waveform fill color" /><input id="waveFillHex" type="text" maxlength="6" inputmode="text" autocomplete="off" spellcheck="false" value="17191C" aria-label="Waveform fill HEX color" /><button class="button" id="waveFillUseWaveColor" type="button">Use Wave Color</button></div></div><div class="wave-fill-image" hidden><div class="wave-fill-upload-row"><span class="wave-fill-image-name">No image selected</span><button class="button accent" id="waveFillUploadBtn" type="button">Upload image</button><input id="waveFillImageFile" type="file" accept="image/*" hidden /></div><label class="wave-fill-zoom">Zoom <span id="waveFillZoomValue">100%</span><input id="waveFillZoom" class="range" type="range" min="100" max="300" value="100" /></label><div class="wave-fill-image-actions"><button class="button" id="waveFillResetCrop" type="button">Reset crop</button></div></div><label class="wave-fill-opacity">Opacity <span id="waveFillOpacityValue">88%</span><input id="waveFillOpacity" class="range" type="range" min="20" max="100" value="88" /></label><p class="hint wave-fill-note">Fill follows the same audio-reactive contour as the waveform.</p>`;colorRow.insertAdjacentElement('afterend',block)}
ui={block:document.querySelector('.wave-fill-block'),enabled:el('waveFillEnabled'),type:el('waveFillType'),colorControls:document.querySelector('.wave-fill-color-controls'),imageControls:document.querySelector('.wave-fill-image'),color:el('waveFillColor'),hex:el('waveFillHex'),useWave:el('waveFillUseWaveColor'),opacity:el('waveFillOpacity'),opacityValue:el('waveFillOpacityValue'),upload:el('waveFillUploadBtn'),file:el('waveFillImageFile'),imageName:document.querySelector('.wave-fill-image-name'),zoom:el('waveFillZoom'),zoomValue:el('waveFillZoomValue'),resetCrop:el('waveFillResetCrop'),note:document.querySelector('.wave-fill-note')};
ui.enabled.addEventListener('change',()=>patch({enabled:ui.enabled.checked}));ui.type.addEventListener('change',()=>{patchImage({type:ui.type.value});if(ui.type.value==='image')patch({enabled:true});syncUI()});ui.color.addEventListener('input',()=>{syncHex();patch({color:ui.color.value})});ui.hex.addEventListener('input',()=>{ui.hex.value=String(ui.hex.value||'').toUpperCase().replace(/[^0-9A-F]/g,'').slice(0,6);if(ui.hex.value.length===6)applyHex()});ui.hex.addEventListener('blur',()=>{if(!applyHex())syncHex()});ui.hex.addEventListener('focus',()=>setTimeout(()=>ui.hex.select(),0));ui.useWave.addEventListener('click',()=>{const info=activeInfo();if(!info)return;patch({color:info.layer.color});syncUI();toast('Fill matched to wave color')});ui.opacity.addEventListener('input',()=>{patch({opacity:+ui.opacity.value});ui.opacityValue.textContent=ui.opacity.value+'%'});ui.upload.addEventListener('click',()=>ui.file.click());ui.file.addEventListener('change',()=>loadImageFile(ui.file.files?.[0]));ui.zoom.addEventListener('input',()=>{patchImage({imageZoom:+ui.zoom.value});ui.zoomValue.textContent=ui.zoom.value+'%'});ui.resetCrop.addEventListener('click',()=>{patchImage({imageX:50,imageY:50,imageZoom:100});syncUI();toast('Image crop reset')});syncLayerResources();syncUI();return true}
function resourceStillUsed(resource,exceptId=null){for(const [id,cfg] of imageState)if(id!==exceptId&&cfg.resource===resource)return true;return false}
function releaseResource(resource,exceptId=null){if(!resource||resourceStillUsed(resource,exceptId))return;if(resource.url)URL.revokeObjectURL(resource.url)}
function setResource(layerId,resource){const cfg=imageState.get(layerId)||{...defaultImageConfig(),resource:null},old=cfg.resource;cfg.resource=resource;cfg.type='image';imageState.set(layerId,cfg);if(old&&old!==resource)releaseResource(old,layerId)}
function loadImageFile(file){if(!file||!file.type?.startsWith('image/'))return;const info=activeInfo();if(!info)return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const now=activeInfo();if(!now||now.layer.id!==info.layer.id){URL.revokeObjectURL(url);return}setResource(info.layer.id,{img,url,name:file.name});patchImage({type:'image',imageX:50,imageY:50,imageZoom:100});patch({enabled:true});ui.file.value='';syncUI();toast('Waveform image loaded')};img.onerror=()=>{URL.revokeObjectURL(url);ui.file.value='';toast('Could not load image')};img.src=url}
function rgba(hex,a){const s=normalizeHex(hex)||'17191C',n=parseInt(s,16);return`rgba(${n>>16},${n>>8&255},${n&255},${clamp(a,0,1)})`}
function drawImageCover(resource,cfg,cx,cy,rad,alpha,pulseScale=1){const img=resource?.img;if(!img?.naturalWidth||!img?.naturalHeight)return;const view=rad*2*1.34,base=Math.max(view/img.naturalWidth,view/img.naturalHeight),zoom=cfg.imageZoom/100,baseDw=img.naturalWidth*base*zoom,baseDh=img.naturalHeight*base*zoom,dw=baseDw*pulseScale,dh=baseDh*pulseScale,maxX=Math.max(0,(baseDw-view)/2),maxY=Math.max(0,(baseDh-view)/2),ox=((cfg.imageX-50)/50)*maxX*pulseScale,oy=((cfg.imageY-50)/50)*maxY*pulseScale;ctx.globalAlpha=alpha;ctx.drawImage(img,cx-dw/2+ox,cy-dh/2+oy,dw,dh)}
function drawFillLayer(frame,w){if(!w.showWave||!FILLABLE.has(w.style))return;const fill=fillFromLayer(w);if(!fill.enabled)return;const r=frame.energy||{bass:0,mid:0,treble:0,beat:0,time:performance.now()/1000},cx=canvas.width*w.x/100,cy=canvas.height*w.y/100,rad=Math.min(canvas.width,canvas.height)*w.size/100*.5,imgCfg=layerImageConfig(w);ctx.save();ctx.shadowBlur=0;ctx.globalCompositeOperation='source-over';G.beginFillPath(ctx,w,r,cx,cy,rad);ctx.fillStyle=rgba(fill.color,fill.opacity/100);ctx.fill();if(imgCfg.type==='image'&&imgCfg.resource){G.beginFillPath(ctx,w,r,cx,cy,rad);ctx.clip();drawImageCover(imgCfg.resource,imgCfg,cx,cy,rad,fill.opacity/100,G.imagePulseScale(w,r))}ctx.restore()}
function drawFills(frame){lastFrame=frame||lastFrame;api.getLayers().forEach(w=>drawFillLayer(frame||lastFrame,w))}pipeline.register('wave','wave-fill',drawFills,-20);
function canvasPoint(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*canvas.width,y:(e.clientY-r.top)/r.height*canvas.height}}
const activeTool=()=>document.querySelector('.tool.active')?.dataset.tool||'';
function isTextHit(x,y){const items=window.__FW_TEXT_BRIDGE?.getItems?.()||[];for(let i=items.length-1;i>=0;i--){const b=items[i]?.bounds;if(b&&x>=b.x-10&&x<=b.x+b.w+10&&y>=b.y-8&&y<=b.y+b.h+8)return true}return false}
function isInsideFill(w,x,y){if(!w?.showWave||!FILLABLE.has(w.style))return false;const fill=fillFromLayer(w),cfg=layerImageConfig(w);if(!fill.enabled||cfg.type!=='image'||!cfg.resource)return false;const r=lastFrame?.energy||{bass:0,mid:0,treble:0,beat:0,time:performance.now()/1000},cx=canvas.width*w.x/100,cy=canvas.height*w.y/100,rad=Math.min(canvas.width,canvas.height)*w.size/100*.5;ctx.save();G.beginFillPath(ctx,w,r,cx,cy,rad);const hit=ctx.isPointInPath(x,y);ctx.restore();return hit}
function imageHit(x,y){const layers=api.getLayers();for(let i=layers.length-1;i>=0;i--)if(isInsideFill(layers[i],x,y))return i;return-1}
function imagePanCapacity(w,cfg){const img=cfg.resource?.img;if(!img?.naturalWidth||!img?.naturalHeight)return{x:1,y:1};const rad=Math.min(canvas.width,canvas.height)*w.size/100*.5,view=rad*2*1.34,base=Math.max(view/img.naturalWidth,view/img.naturalHeight),scale=base*(cfg.imageZoom/100),dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;return{x:Math.max(1,(dw-view)/2),y:Math.max(1,(dh-view)/2)}}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||!e.isTrusted||activeTool()!=='waveform')return;const p=canvasPoint(e);if(isTextHit(p.x,p.y))return;const index=imageHit(p.x,p.y);if(index<0)return;api.selectLayer?.(index);const layer=api.getLayers()[index],cfg=layerImageConfig(layer);cropDrag={pointerId:e.pointerId,index,layerId:layer.id,startClientX:e.clientX,startClientY:e.clientY,startX:cfg.imageX,startY:cfg.imageY};try{canvas.setPointerCapture(e.pointerId)}catch{}canvas.style.cursor='grabbing';e.preventDefault();e.stopImmediatePropagation()},true);
document.addEventListener('pointermove',e=>{if(!cropDrag||e.pointerId!==cropDrag.pointerId)return;const layers=api.getLayers(),layer=layers[cropDrag.index];if(!layer||layer.id!==cropDrag.layerId){cropDrag=null;return}const cfg=layerImageConfig(layer),cap=imagePanCapacity(layer,cfg),rect=canvas.getBoundingClientRect(),dx=(e.clientX-cropDrag.startClientX)/rect.width*canvas.width,dy=(e.clientY-cropDrag.startClientY)/rect.height*canvas.height;cfg.imageX=clamp(cropDrag.startX+dx/(cap.x*2)*100,0,100);cfg.imageY=clamp(cropDrag.startY+dy/(cap.y*2)*100,0,100);e.preventDefault();e.stopImmediatePropagation()},true);
function endCrop(e){if(!cropDrag||e.pointerId!==cropDrag.pointerId)return;cropDrag=null;try{canvas.releasePointerCapture(e.pointerId)}catch{}canvas.style.cursor=activeTool()==='waveform'?'move':'default';e.preventDefault();e.stopImmediatePropagation()}document.addEventListener('pointerup',endCrop,true);document.addEventListener('pointercancel',endCrop,true);
if(!api.__fillHitPatched){const baseHit=api.hitTest?.bind(api);api.hitTest=(x,y)=>{const hit=baseHit?baseHit(x,y):-1;if(hit>=0)return hit;const layers=api.getLayers();for(let i=layers.length-1;i>=0;i--){const w=layers[i],fill=fillFromLayer(w);if(!w.showWave||!fill.enabled||!FILLABLE.has(w.style))continue;const b=api.getBounds(i);if(!b)continue;const nx=(x-b.cx)/(b.w/2||1),ny=(y-b.cy)/(b.h/2||1);if(Math.hypot(nx,ny)<=1.02)return i}return-1};api.__fillHitPatched=true}
function syncLayerResources(){const layers=api.getLayers(),ids=layers.map(w=>w.id),newIds=ids.filter(id=>!lastLayerIds.includes(id)),isSingleClone=newIds.length===1&&ids.length===lastLayerIds.length+1;if(isSingleClone&&lastActiveId&&imageState.has(lastActiveId)){const source=imageState.get(lastActiveId);imageState.set(newIds[0],{...source,resource:source.resource})}for(const [id,cfg] of [...imageState]){if(ids.includes(id))continue;imageState.delete(id);if(cfg.resource&&!resourceStillUsed(cfg.resource))releaseResource(cfg.resource)}lastLayerIds=ids;lastActiveId=layers[api.getActiveIndex()]?.id||null}
function clearImages(){const resources=new Set([...imageState.values()].map(x=>x.resource).filter(Boolean));resources.forEach(r=>{if(r.url)URL.revokeObjectURL(r.url)});imageState.clear();lastLayerIds=[];lastActiveId=null}
document.addEventListener('click',e=>{if(!e.target.closest?.('[data-template],[data-creative]'))return;const info=activeInfo();if(!info)return;const keep=current(),keepImg={...currentImage()};queueMicrotask(()=>{const now=activeInfo();if(now&&now.index===info.index){patch(keep);Object.assign(layerImageConfig(now.layer),keepImg);syncUI()}})},true);
function relabelPresetCopy(){const card=document.querySelector('.user-presets-card');if(!card)return;const sub=card.querySelector('.card-title small'),hint=card.querySelector('.hint');if(sub)sub.textContent='Wave layers + Fill + Wave Look + Free Text';if(hint)hint.textContent='Saves waveform layout, Color Fill, Global Wave Look and Free Text. Uploaded Fill images stay local to the current session.'}
mount();setTimeout(relabelPresetCopy,0);document.querySelector('.tool[data-tool="presets"]')?.addEventListener('click',()=>requestAnimationFrame(relabelPresetCopy));document.addEventListener('fw:wave-selection-change',()=>{syncLayerResources();syncUI()});document.addEventListener('fw:wave-setting-change',()=>{syncLayerResources();syncUI()});document.addEventListener('fw:plate-change',syncUI);document.addEventListener('fw:project-reset',()=>{clearImages();requestAnimationFrame(()=>{syncLayerResources();syncUI()})});window.addEventListener('beforeunload',clearImages);
window.__FW_WAVE_FILL={defaults:{...DEFAULT_FILL},getConfig:()=>({...current(),...currentImage(),hasImage:!!currentImage().resource}),setConfig:(value={})=>{const imagePatch={},colorPatch={};['type','imageX','imageY','imageZoom'].forEach(k=>{if(value[k]!==undefined)imagePatch[k]=value[k]});if(Object.keys(imagePatch).length)patchImage(imagePatch);['enabled','color','opacity'].forEach(k=>{if(value[k]!==undefined)colorPatch[k]=value[k]});if(Object.keys(colorPatch).length)patch(colorPatch);syncUI();return true}};
})();