(()=>{
'use strict';
const api=window.__FW_MULTI_WAVE,C=window.__FW_WAVE_CONFIG,pipeline=window.__FW_RENDER_PIPELINE,canvas=document.getElementById('canvas');if(!api||!C||!pipeline||!canvas)return;
const ctx=canvas.getContext('2d'),U=window.__FW_UTILS||{},clamp=U.clamp||((v,a,b)=>Math.max(a,Math.min(b,v))),lerp=U.lerp||((a,b,t)=>a+(b-a)*t),normalizeHex=U.normalizeHex||(v=>String(v||'').replace(/^#/,'').toUpperCase().replace(/[^0-9A-F]/g,'').slice(0,6)),toast=window.__FW_TOAST||(()=>{}),{DEFAULT_FILL,FILLABLE}=C,el=id=>document.getElementById(id);let ui=null;
function fillFromLayer(layer){const p=layer?.plate||{},color=p.tone==='light'?'#f2eee5':(/^#[0-9a-f]{6}$/i.test(String(p.color||''))?p.color:DEFAULT_FILL.color);return{enabled:!!p.enabled,color,opacity:clamp(Number.isFinite(+p.opacity)?+p.opacity:DEFAULT_FILL.opacity,20,100)}}
function activeInfo(){const layers=api.getLayers(),index=api.getActiveIndex(),layer=layers[index];return layer?{index,layer}:null}
function current(){return fillFromLayer(activeInfo()?.layer)}
function patch(value){const info=activeInfo();if(!info)return false;const next={...current(),...value};return api.updatePlate(info.index,{enabled:!!next.enabled,color:next.color,opacity:clamp(+next.opacity||DEFAULT_FILL.opacity,20,100),tone:'custom',shape:'follow',softness:0,shadow:0,size:100})}
function syncHex(){if(ui)ui.hex.value=normalizeHex(ui.color.value)||'17191C'}
function syncAvailability(){if(!ui)return;const info=activeInfo(),ok=!!info&&FILLABLE.has(info.layer.style);[ui.enabled,ui.color,ui.hex,ui.useWave,ui.opacity].forEach(x=>x.disabled=!ok);ui.block.classList.toggle('disabled',!ok);ui.note.textContent=ok?'Fill follows the same audio-reactive contour as the waveform. Text always renders above it.':'Fill is available for Brush Ring, Smooth Ring, Radial Bars and Orbit Dots.'}
function syncUI(){if(!ui)return;const c=current();ui.enabled.checked=c.enabled;ui.color.value=c.color;ui.opacity.value=c.opacity;ui.opacityValue.textContent=c.opacity+'%';syncHex();syncAvailability()}
function applyHex(){const clean=normalizeHex(ui.hex.value);if(!clean)return false;ui.hex.value=clean;ui.color.value='#'+clean;patch({color:'#'+clean});return true}
function mountStyles(){if(el('fw-wave-fill-style'))return;const s=document.createElement('style');s.id='fw-wave-fill-style';s.textContent=`.wave-fill-block{margin:10px 0;padding:10px;border:1px solid #2b3033;border-radius:10px;background:rgba(8,12,14,.58)}.wave-fill-title{margin:0 0 8px}.wave-fill-enable{display:flex!important;align-items:center;gap:7px;font-size:10px!important;font-weight:600;color:#ddd3c5!important;margin:0 0 9px!important}.wave-fill-row{display:grid;grid-template-columns:46px minmax(72px,1fr) minmax(112px,auto);align-items:center;gap:6px}.wave-fill-row input[type=color]{width:46px;height:36px;border:1px solid #30363a;border-radius:8px;background:#0b0f11;padding:3px}.wave-fill-row input[type=text]{height:36px;margin:0!important;padding:0 9px!important;border:1px solid #30363a!important;border-radius:8px!important;background:#0b0f11!important;color:#eee6da!important;font:600 10px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace!important;letter-spacing:.06em;text-transform:uppercase}.wave-fill-row .button{height:36px;min-height:36px}.wave-fill-opacity{display:block!important;margin:9px 0 0!important}.wave-fill-note{margin:6px 0 0!important}.wave-fill-block.disabled{opacity:.55}.wave-fill-block.disabled .wave-fill-title{color:#777}@media(max-width:820px){.wave-fill-row{grid-template-columns:46px 1fr}.wave-fill-row .button{grid-column:1/-1;width:100%}}`;document.head.appendChild(s)}
function mount(){const card=el('waveStyle')?.closest('.card'),colorRow=card?.querySelector('.color-row');if(!card||!colorRow)return false;mountStyles();if(!el('waveFillEnabled')){const block=document.createElement('div');block.className='wave-fill-block';block.innerHTML=`<div class="section-label wave-fill-title">FILL</div><label class="wave-fill-enable"><input id="waveFillEnabled" type="checkbox" /> Fill inside waveform</label><div class="wave-fill-row"><input id="waveFillColor" type="color" value="#17191c" aria-label="Waveform fill color" /><input id="waveFillHex" type="text" maxlength="6" inputmode="text" autocomplete="off" spellcheck="false" value="17191C" aria-label="Waveform fill HEX color" /><button class="button" id="waveFillUseWaveColor" type="button">Use Wave Color</button></div><label class="wave-fill-opacity">Opacity <span id="waveFillOpacityValue">88%</span><input id="waveFillOpacity" class="range" type="range" min="20" max="100" value="88" /></label><p class="hint wave-fill-note">Fill follows the same audio-reactive contour as the waveform. Text always renders above it.</p>`;colorRow.insertAdjacentElement('afterend',block)}ui={block:document.querySelector('.wave-fill-block'),enabled:el('waveFillEnabled'),color:el('waveFillColor'),hex:el('waveFillHex'),useWave:el('waveFillUseWaveColor'),opacity:el('waveFillOpacity'),opacityValue:el('waveFillOpacityValue'),note:document.querySelector('.wave-fill-note')};ui.enabled.addEventListener('change',()=>patch({enabled:ui.enabled.checked}));ui.color.addEventListener('input',()=>{syncHex();patch({color:ui.color.value})});ui.hex.addEventListener('input',()=>{ui.hex.value=String(ui.hex.value||'').toUpperCase().replace(/[^0-9A-F]/g,'').slice(0,6);if(ui.hex.value.length===6)applyHex()});ui.hex.addEventListener('blur',()=>{if(!applyHex())syncHex()});ui.hex.addEventListener('focus',()=>setTimeout(()=>ui.hex.select(),0));ui.useWave.addEventListener('click',()=>{const info=activeInfo();if(!info)return;patch({color:info.layer.color});syncUI();toast('Fill matched to wave color')});ui.opacity.addEventListener('input',()=>{patch({opacity:+ui.opacity.value});ui.opacityValue.textContent=ui.opacity.value+'%'});syncUI();return true}
function rgba(hex,a){const s=normalizeHex(hex)||'17191C',n=parseInt(s,16);return`rgba(${n>>16},${n>>8&255},${n&255},${clamp(a,0,1)})`}
function poly(shape){let n=0,rot=-Math.PI/2;if(shape==='triangle')n=3;if(shape==='square')n=4;if(shape==='diamond'){n=4;rot=0}if(shape==='pentagon')n=5;if(shape==='hexagon')n=6;if(shape==='octagon')n=8;if(!n)return null;return Array.from({length:n},(_,i)=>({x:Math.cos(rot+i*Math.PI*2/n),y:Math.sin(rot+i*Math.PI*2/n)}))}
function shapePoint(shape,t,r){const a=t*Math.PI*2-Math.PI/2;if(shape==='circle')return{x:Math.cos(a)*r,y:Math.sin(a)*r};if(shape==='lotus'){const rr=r*(.8+.2*Math.abs(Math.sin(a*4)));return{x:Math.cos(a)*rr,y:Math.sin(a)*rr}}if(shape==='blob'){const rr=r*(.9+.055*Math.sin(a*3+1.1)+.045*Math.sin(a*7+2.7)+.025*Math.sin(a*13));return{x:Math.cos(a)*rr,y:Math.sin(a)*rr}}if(shape==='star'){const count=10,u=(t*count)%1,i=Math.floor(t*count),aa=-Math.PI/2+i*Math.PI*2/count,ab=-Math.PI/2+(i+1)*Math.PI*2/count,ra=i%2===0?r:r*.48,rb=(i+1)%2===0?r:r*.48;return{x:lerp(Math.cos(aa)*ra,Math.cos(ab)*rb,u),y:lerp(Math.sin(aa)*ra,Math.sin(ab)*rb,u)}}const v=poly(shape)||poly('hexagon'),n=v.length,pos=t*n,i=Math.floor(pos)%n,u=pos-i,p=v[i],q=v[(i+1)%n];return{x:lerp(p.x,q.x,u)*r,y:lerp(p.y,q.y,u)*r}}
function pseudoBin(q,r,w){const low=r.bass*Math.pow(1-q,.9),mid=r.mid*Math.pow(Math.sin(Math.PI*q),2),hi=r.treble*Math.pow(q,.8),ripple=.52+.48*Math.abs(Math.sin(q*(29+w.detail*.11)+r.time*(2.2+r.treble*2)));return clamp((low*.8+mid*.65+hi*.55)*ripple+r.beat*.08,0,1.4)}
function punch(r,w){return clamp(r.beat*(w.beatPunch/100),0,3)}
function ringPath(w,r,cx,cy,rad){const N=Math.max(160,Math.round(w.detail*2.5)),dep=w.toothDepth/100,p=punch(r,w),rough=w.style==='brushRing'?1.25:0;ctx.beginPath();for(let i=0;i<=N;i++){const t=(i%N)/N,sp=shapePoint(w.shape,t,rad),b=Math.pow(pseudoBin(t,r,w),lerp(.72,2.2,w.sharpness/100)),tri=1-Math.abs(((t*w.detail)%1)*2-1),tooth=(Math.pow(clamp(tri,0,1),lerp(.7,5.4,w.sharpness/100))-.28)*dep*.06,m=1+clamp(b*(w.reaction/100)+p*.25,0,3)*.095+tooth+(rough?Math.sin(i*2.31)*rough*.01:0),x=cx+sp.x*m,y=cy+sp.y*m;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath()}
function radialPath(w,r,cx,cy,rad){const N=clamp(Math.round(w.detail),24,256),depth=w.toothDepth/100,p=punch(r,w);ctx.beginPath();for(let i=0;i<=N;i++){const t=(i%N)/N,sp=shapePoint(w.shape,t,rad),b=pseudoBin(t,r,w),react=clamp(b*(.10+depth*.15)*(w.reaction/100)+p*(.045+depth*.055),0,.9),len=rad*(.018+react),mag=Math.hypot(sp.x,sp.y)||1,x=cx+sp.x+sp.x/mag*len,y=cy+sp.y+sp.y/mag*len;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath()}
function drawFillLayer(frame,w){if(!w.showWave||!FILLABLE.has(w.style))return;const fill=fillFromLayer(w);if(!fill.enabled)return;const r=frame.energy||{bass:0,mid:0,treble:0,beat:0,time:performance.now()/1000},cx=canvas.width*w.x/100,cy=canvas.height*w.y/100,rad=Math.min(canvas.width,canvas.height)*w.size/100*.5;ctx.save();ctx.shadowBlur=0;ctx.globalCompositeOperation='source-over';ctx.fillStyle=rgba(fill.color,fill.opacity/100);if(w.style==='brushRing'||w.style==='smoothRing')ringPath(w,r,cx,cy,rad);else radialPath(w,r,cx,cy,rad);ctx.fill();ctx.restore()}
function drawFills(frame){api.getLayers().forEach(w=>drawFillLayer(frame,w))}pipeline.register('wave','wave-fill',drawFills,-20);
if(!api.__fillHitPatched){const baseHit=api.hitTest?.bind(api);api.hitTest=(x,y)=>{const hit=baseHit?baseHit(x,y):-1;if(hit>=0)return hit;const layers=api.getLayers();for(let i=layers.length-1;i>=0;i--){const w=layers[i],fill=fillFromLayer(w);if(!w.showWave||!fill.enabled||!FILLABLE.has(w.style))continue;const b=api.getBounds(i);if(!b)continue;const nx=(x-b.cx)/(b.w/2||1),ny=(y-b.cy)/(b.h/2||1);if(Math.hypot(nx,ny)<=1.02)return i}return-1};api.__fillHitPatched=true}
// Fill is a visual property, independent of template choice. Preserve it when switching built-in/creative presets.
document.addEventListener('click',e=>{if(!e.target.closest?.('[data-template],[data-creative]'))return;const info=activeInfo();if(!info)return;const keep=current();queueMicrotask(()=>{const now=activeInfo();if(now&&now.index===info.index){patch(keep);syncUI()}})},true);
function relabelPresetCopy(){const card=document.querySelector('.user-presets-card');if(!card)return;const sub=card.querySelector('.card-title small'),hint=card.querySelector('.hint');if(sub)sub.textContent='Wave layers + Fill + Wave Look + text';if(hint)hint.textContent='Saves all waveform layers, waveform Fill, Global Wave Look, text content/styles and positions. Background media is not stored.'}
mount();setTimeout(relabelPresetCopy,0);document.querySelector('.tool[data-tool="presets"]')?.addEventListener('click',()=>requestAnimationFrame(relabelPresetCopy));document.addEventListener('fw:wave-selection-change',syncUI);document.addEventListener('fw:wave-setting-change',syncUI);document.addEventListener('fw:plate-change',syncUI);document.addEventListener('fw:project-reset',()=>requestAnimationFrame(syncUI));window.__FW_WAVE_FILL={defaults:{...DEFAULT_FILL},getConfig:()=>({...current()}),setConfig:(value={})=>{const ok=patch(value);syncUI();return ok}};
})();
